apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-client-provisioner
      version: 	"1.2.11"
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: flux-system
      interval: 1m
  releaseName: nfs-provisioner
  targetNamespace: storage
  values:
    nfs:
      server: 192.168.86.27
      path: /mnt/nfs_share
    image:
      repository: quay.io/external_storage/nfs-client-provisioner-arm