---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph-backend
  namespace: flux-system
spec:
  dependsOn:
  - name: rook-ceph-common
  interval: 10m0s
  path: ./staging-cluster/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: rook-ceph
  validation: client

