---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph-common
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./staging-cluster/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: rook-ceph
  validation: client

